jobs:
  server-tests:
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: 'true'
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: '/var/run/docker.sock'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - run: docker info   # quick sanity check

      - run: npm ci

      - name: Ensure upload dir exists
        run: mkdir -p apps/server/uploads

      - name: Generate Prisma client
        run: npm -w apps/server run prisma:generate

      - name: Build server (fail fast on TS)
        run: npm -w apps/server run build

      - name: Run server tests
        run: npm -w apps/server run test

  web-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - run: npm ci
      - name: Run web unit tests
        run: npm -w apps/web run test
      - name: Typecheck web
        run: npm -w apps/web run typecheck

  build:
    needs: [server-tests, web-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm -w apps/server run prisma:generate
      - run: npm -w apps/server run build
      - run: npm -w apps/web run build
